# Generated by Django 5.2 on 2025-05-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0004_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="project_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_set",
                to="novacartografia_employee_management.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[("obra", "Obra"), ("proyecto", "Proyecto")],
                default="proyecto",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeNeeded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("topo", "Topo"), ("auxiliar", "Auxiliar")],
                        default="topo",
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fulfilled", models.BooleanField(default=False)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novacartografia_employee_management.project",
                    ),
                ),
            ],
        ),
    ]
