# Generated by Django 5.2 on 2025-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0007_employee_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="academic_training",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="building",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="confine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="drag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="driver_license",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="leveling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="mining",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="office_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="railway_carriage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="railway_mounting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="scanner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="sixty_hours",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="static",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="twenty_hours",
            field=models.BooleanField(default=False),
        ),
    ]
