# Generated by Django 5.2 on 2025-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0008_employee_academic_training_employee_building_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
