# Generated by Django 5.2 on 2025-05-12 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0010_project_academic_training_project_building_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="driver_license",
        ),
    ]
