# Generated by Django 5.2 on 2025-05-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0011_remove_project_driver_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.CharField(
                choices=[
                    ("alava", "Álava"),
                    ("albacete", "Albacete"),
                    ("alicante", "Alicante"),
                    ("almeria", "Almería"),
                    ("asturias", "Asturias"),
                    ("avila", "Ávila"),
                    ("badajoz", "Badajoz"),
                    ("barcelona", "Barcelona"),
                    ("burgos", "Burgos"),
                    ("caceres", "Cáceres"),
                    ("cadiz", "Cádiz"),
                    ("cantabria", "Cantabria"),
                    ("castellon", "Castellón"),
                    ("ceuta", "Ceuta"),
                    ("ciudad_real", "Ciudad Real"),
                    ("cordoba", "Córdoba"),
                    ("cuenca", "Cuenca"),
                    ("gerona", "Gerona"),
                    ("granada", "Granada"),
                    ("guadalajara", "Guadalajara"),
                    ("guipuzcoa", "Guipúzcoa"),
                    ("huelva", "Huelva"),
                    ("huesca", "Huesca"),
                    ("islas_baleares", "Islas Baleares"),
                    ("jaen", "Jaén"),
                    ("la_coruna", "La Coruña"),
                    ("la_rioja", "La Rioja"),
                    ("las_palmas", "Las Palmas"),
                    ("leon", "León"),
                    ("lerida", "Lérida"),
                    ("lugo", "Lugo"),
                    ("madrid", "Madrid"),
                    ("malaga", "Málaga"),
                    ("melilla", "Melilla"),
                    ("murcia", "Murcia"),
                    ("navarra", "Navarra"),
                    ("orense", "Orense"),
                    ("palencia", "Palencia"),
                    ("pontevedra", "Pontevedra"),
                    ("salamanca", "Salamanca"),
                    ("santa_cruz_de_tenerife", "Santa Cruz de Tenerife"),
                    ("segovia", "Segovia"),
                    ("sevilla", "Sevilla"),
                    ("soria", "Soria"),
                    ("tarragona", "Tarragona"),
                    ("teruel", "Teruel"),
                    ("toledo", "Toledo"),
                ],
                default="valencia",
                max_length=50,
            ),
        ),
    ]
