# Generated by Django 5.2 on 2025-05-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0014_employee_locked_alter_project_state",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee is locked for a future project",
            ),
        ),
        migrations.CreateModel(
            name="GetEmployeeLocked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="When the employee should start in the new project"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fulfilled",
                    models.BooleanField(
                        default=False,
                        help_text="When marked as fulfilled, the employee will be assigned to the new project",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        help_text="The employee to be assigned to the project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_assignment",
                        to="novacartografia_employee_management.employee",
                    ),
                ),
                (
                    "next_project",
                    models.ForeignKey(
                        help_text="The project the employee will be assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_employee_assignments",
                        to="novacartografia_employee_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Future Employee Assignment",
                "verbose_name_plural": "Future Employee Assignments",
            },
        ),
    ]
