# Generated by Django 5.2 on 2025-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0015_alter_employee_locked_getemployeelocked",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="getemployeelocked",
            name="employee",
        ),
        migrations.AddField(
            model_name="getemployeelocked",
            name="employee",
            field=models.ManyToManyField(
                help_text="The employee to be assigned to the project",
                related_name="future_assignment",
                to="novacartografia_employee_management.employee",
            ),
        ),
    ]
