# Generated by Django 5.2 on 2025-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0017_remove_getemployeelocked_employee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="getemployeelocked",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="When the employee should end in the new project",
                null=True,
            ),
        ),
    ]
