# Generated by Django 5.2 on 2025-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0018_getemployeelocked_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="manager",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Jose Cuesta Mejías", "Cuesta"),
                    ("Javier Marín Gimeno", "Javi"),
                    ("Guillermo Boscá Gómez", "Guillermo"),
                    ("Miguel Ángel Martínez García", "Miguel Ángel"),
                    ("Óscar López Valverde", "Óscar"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[("external", "Obra"), ("project", "Proyecto")],
                default="proyecto",
                max_length=50,
            ),
        ),
    ]
