# Generated by Django 5.2 on 2025-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0019_alter_project_manager_alter_project_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
