# Generated by Django 5.2 on 2025-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0020_employee_city_employee_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=models.CharField(
                choices=[
                    ("Álava", "Álava"),
                    ("Albacete", "Albacete"),
                    ("Alicante", "Alicante"),
                    ("Almería", "Almería"),
                    ("Asturias", "Asturias"),
                    ("Ávila", "Ávila"),
                    ("Badajoz", "Badajoz"),
                    ("Barcelona", "Barcelona"),
                    ("Burgos", "Burgos"),
                    ("Cáceres", "Cáceres"),
                    ("Cádiz", "Cádiz"),
                    ("Cantabria", "Cantabria"),
                    ("Castellón", "Castellón"),
                    ("Ceuta", "Ceuta"),
                    ("Ciudad Real", "Ciudad Real"),
                    ("Córdoba", "Córdoba"),
                    ("Cuenca", "Cuenca"),
                    ("Gerona", "Gerona"),
                    ("Granada", "Granada"),
                    ("Guadalajara", "Guadalajara"),
                    ("Guipúzcoa", "Guipúzcoa"),
                    ("Huelva", "Huelva"),
                    ("Huesca", "Huesca"),
                    ("Islas Baleares", "Islas Baleares"),
                    ("Jaén", "Jaén"),
                    ("La Coruña", "La Coruña"),
                    ("La Rioja", "La Rioja"),
                    ("Las Palmas", "Las Palmas"),
                    ("León", "León"),
                    ("Lérida", "Lérida"),
                    ("Lugo", "Lugo"),
                    ("Madrid", "Madrid"),
                    ("Málaga", "Málaga"),
                    ("Melilla", "Melilla"),
                    ("Murcia", "Murcia"),
                    ("Navarra", "Navarra"),
                    ("Orense", "Orense"),
                    ("Palencia", "Palencia"),
                    ("Pontevedra", "Pontevedra"),
                    ("Salamanca", "Salamanca"),
                    ("Santa Cruz de Tenerife", "Santa Cruz de Tenerife"),
                    ("Segovia", "Segovia"),
                    ("Sevilla", "Sevilla"),
                    ("Soria", "Soria"),
                    ("Tarragona", "Tarragona"),
                    ("Teruel", "Teruel"),
                    ("Toledo", "Toledo"),
                    ("Valencia", "Valencia"),
                    ("Valladolid", "Valladolid"),
                    ("Vizcaya", "Vizcaya"),
                    ("Zamora", "Zamora"),
                    ("Zaragoza", "Zaragoza"),
                ],
                default="valencia",
                max_length=50,
            ),
        ),
    ]
