# Generated by Django 5.2 on 2025-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0022_alter_employee_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
