# Generated by Django 5.2 on 2025-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0023_employee_latitude_employee_longitude",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="height",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="height",
            field=models.BooleanField(default=False),
        ),
    ]
