# Generated by Django 5.2 on 2025-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0025_alter_project_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
