# Generated by Django 5.2 on 2025-06-04 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0026_alter_project_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Indicates if the employee is currently active"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="When the employee ended working, if applicable",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="When the employee started working",
            ),
        ),
    ]
