# Generated by Django 5.2 on 2025-06-09 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0027_employee_active_employee_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="When the employee started working",
                null=True,
            ),
        ),
    ]
