# Generated by Django 5.2 on 2025-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0028_alter_employee_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeneeded",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
