# Generated by Django 5.2 on 2025-08-27 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0029_employeeneeded_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
