# Generated by Django 5.2 on 2025-08-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0030_project_date_from_project_date_to",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
