# Generated by Django 5.2 on 2025-09-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0031_alter_project_date_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="vacations_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="vacations_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
