# Generated by Django 5.2 on 2025-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0032_employee_vacations_from_employee_vacations_to",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="leave_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="leave_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
