# Generated by Django 5.2 on 2025-09-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "novacartografia_employee_management",
            "0033_employee_leave_from_employee_leave_to",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeVacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="novacartografia_employee_management.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Holiday",
                "verbose_name_plural": "Employee Holidays",
                "ordering": ["date_from"],
            },
        ),
    ]
