# Generated by Django 5.2 on 2025-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0034_employeevacation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
