# Generated by Django 5.2 on 2025-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novacartografia_employee_management", "0035_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="end_contract",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee's contract is ending soon",
            ),
        ),
    ]
