# Generated by Django 5.2 on 2025-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacartografia_employee_management', '0036_employee_end_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_contract_date',
            field=models.DateField(blank=True, help_text="Date when the employee's contract is ending", null=True),
        ),
    ]
