# Generated by Django 5.2 on 2025-10-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novacartografia_employee_management', '0037_employee_end_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeneeded',
            name='partial_fulfillment',
            field=models.BooleanField(default=False),
        ),
    ]
