# Generated by Django 5.2 on 2025-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_maps", "0002_bigprojectlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigprojectlocation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
