# Generated by Django 5.2 on 2025-09-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_maps", "0003_bigprojectlocation_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bigprojectlocation",
            options={
                "ordering": ["-amount", "name"],
                "verbose_name": "Gran Proyecto",
                "verbose_name_plural": "Grandes Proyectos",
            },
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Importe en euros",
                max_digits=12,
                verbose_name="Importe",
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="country",
            field=models.CharField(
                default="España", max_length=100, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="developer",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Desarrollador/Constructor",
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="latitude",
            field=models.FloatField(verbose_name="Latitud"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="longitude",
            field=models.FloatField(verbose_name="Longitud"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre del Proyecto"),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Provincia"
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Inicio"
            ),
        ),
        migrations.AlterField(
            model_name="bigprojectlocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
        ),
        migrations.AlterModelTable(
            name="bigprojectlocation",
            table="project_maps_bigprojectlocation",
        ),
    ]
